import UIKit
import Components
import ImagesService

public struct CheckboxViewStyle {
    
    public typealias Selection = CheckboxVariables.Selection
    public typealias State = CheckboxVariables.State
    
    private var variables: CheckboxVariables
    public var selection: Selection {
        get { variables.selection }
        set { variables.selection = newValue }
    }
    public var state: State {
        get { variables.state }
        set { variables.state = newValue }
    }
    
    public init(
        selection: Selection,
        state: State
    ) {
        self.variables = .init(selection: selection, state: state)
    }
    
    public func update(
        viewProperties: inout CheckboxView.ViewProperties
    ) {
        viewProperties.backgroundColor = variables.backgroundColor()
        viewProperties.size = .init(width: 20, height: 20)
        viewProperties.cornerRadius = viewProperties.size.width / 2
        viewProperties.borderColor = variables.borderColor()
        viewProperties.borderWidth = variables.borderWidth()
        viewProperties.checkIcon = variables.checkIcon()
        viewProperties.isUserInteractionEnabled = state != .disabled
    }
}

public struct CheckboxVariables {
    
    public enum Selection: String {
        case `default`
        case checked
    }
    
    public enum State: String {
        case `default`
        case pressed
        case disabled
    }
    
    public var selection: Selection
    public var state: State
    
    public init(
        selection: Selection,
        state: State
    ) {
        self.selection = selection
        self.state = state
    }
    
    public func backgroundColor() -> UIColor {
        let hexString = checkbox[selection.rawValue]?["background"]?["color"]?[state.rawValue]?["value"] ?? ""
        return UIColor(hexString: hexString)
    }
    
    public func borderColor() -> UIColor {
        let hexString = checkbox[selection.rawValue]?["border"]?["color"]?[state.rawValue]?["value"] ?? ""
        return UIColor(hexString: hexString)
    }
    
    public func borderWidth() -> CGFloat {
        switch selection {
        case .checked: 0
        case .default: 1
        }
    }
    
    public func checkIcon() -> UIImage? {
        let hexString = checkbox[selection.rawValue]?["checkIcon"]?["color"]?[state.rawValue]?["value"] ?? ""
        return .ic10Check.withTintColor(UIColor(hexString: hexString))
    }
    
    // MARK: "AUTOGENERATED" FROM JSON
    
    private let checkbox: [String: [String: [String: [String: [String: String]]]]] = [
        "default": [
            "background": [
                "color": [
                    "default": ["value": "#F5F5F5"],
                    "pressed": ["value": "#E0E0E0"],
                    "disabled": ["value": "#E8E8E8"]
                ]
            ],
            "border": [
                "color": [
                    "default": ["value": "#C8C6C6"],
                    "pressed": ["value": "#A1A0A0"],
                    "disabled": ["value": "#C8C6C6"]
                ]
            ],
            "checkIcon": [
                "color": [
                    "default": ["value": "#FFFFFF00"],
                    "pressed": ["value": "#FFFFFF00"],
                    "disabled": ["value": "#FFFFFF00"]
                ]
            ]
        ],
        "checked": [
            "background": [
                "color": [
                    "default": ["value": "#009B3A"],
                    "pressed": ["value": "#006625"],
                    "disabled": ["value": "#ADEBC4"]
                ]
            ],
            "border": [
                "color": [
                    "default": ["value": "#FFFFFF00"],
                    "pressed": ["value": "#FFFFFF00"],
                    "disabled": ["value": "#FFFFFF00"]
                ]
            ],
            "checkIcon": [
                "color": [
                    "default": ["value": "#FFFFFF"],
                    "pressed": ["value": "#FFFFFF"],
                    "disabled": ["value": "#FFFFFF"]
                ]
            ]
        ]
    ]
}
