import UIKit
import Components
import Colors

public struct ImageViewStyle {
    
    public enum Variant {
        /// Tinted icon
        case icon(UIImage)
        /// Tinted letters
        case letters(NSMutableAttributedString)
        /// 40x40 image
        case image(UIImage)
    }
    
    public typealias Color = ImageVariables.Color
    
    private let variant: Variant
    private let variables: ImageVariables
    
    public init(
        variant: Variant,
        color: Color
    ) {
        self.variant = variant
        self.variables = .init(color: color)
    }
    
    public func update(
        viewProperties: inout ImageView.ViewProperties
    ) {
        viewProperties.size = .init(width: 40, height: 40)
        viewProperties.backgroundColor = variables.backgroundColor()
        viewProperties.cornerRadius = 20
        viewProperties.text = variant.text()?
            .fontStyle(.textM)
            .foregroundColor(variables.labelColor())
        viewProperties.image = variant.image(tintColor: variables.iconColor())
    }
}

public extension ImageViewStyle.Variant {
    
    func image(tintColor: UIColor) -> UIImage? {
        switch self {
        case .icon(let image): image.withTintColor(tintColor)
        case .letters: nil
        case .image(let image): image
        }
    }
    
    func text() -> NSMutableAttributedString? {
        switch self {
        case .icon: nil
        case .letters(let text): text
        case .image: nil
        }
    }
}

// MARK: SHOULD BE AUTOGENERATED FROM TOKENS JSON

public struct ImageVariables {
    
    public enum Color: String {
        case primary
        case main
        case mainInverse
        case additional1 = "add1"
        case additional2 = "add2"
        case additional3 = "add3"
        case additional4 = "add4"
        case additional5 = "add5"
        case additional6 = "add6"
        case additional7 = "add7"
        case additional8 = "add8"
    }
    
    private let color: Color
    
    public init(
        color: Color
    ) {
        self.color = color
    }
    
    public func backgroundColor() -> UIColor {
        let hexString = image[color.rawValue]?["background"]?["color"] ?? ""
        return UIColor(hexString: hexString)
    }
    
    public func iconColor() -> UIColor {
        let hexString = image[color.rawValue]?["icon"]?["color"] ?? ""
        return UIColor(hexString: hexString)
    }
    
    public func labelColor() -> UIColor {
        let hexString = image[color.rawValue]?["label"]?["color"] ?? ""
        return UIColor(hexString: hexString)
    }
    
    // заменится на общий token-json
    private let image: [String: [String: [String: String]]] = [
        "primary": [
            "background": ["color": "#F5F5F5"],
            "icon": ["color": "#6E6D6D"],
            "label": ["color": "#6E6D6D"]],
        "main": [
            "background": ["color": "#FFFFFF"],
            "icon": ["color": "#6E6D6D"],
            "label": ["color": "#6E6D6D"]],
        "mainInverse": [
            "background": ["color": "#141414"],
            "icon": ["color": "#FFFFFF"],
            "label": ["color": "#FFFFFF"]],
        "add1": [
            "background": ["color": "#009B3A"],
            "icon": ["color": "#FFFFFF"]],
        "add2": [
            "background": ["color": "#EC4661"],
            "icon": ["color": "#FFFFFF"]],
        "add3": [
            "background": ["color": "#F3B925"],
            "icon": ["color": "#FFFFFF"]],
        "add4": [
            "background": ["color": "#6693CB"],
            "icon": ["color": "#FFFFFF"]],
        "add5": [
            "background": ["color": "#936EB9"],
            "icon": ["color": "#FFFFFF"]],
        "add6": [
            "background": ["color": "#03B3A8"],
            "icon": ["color": "#FFFFFF"]],
        "add7": [
            "background": ["color": "#16AE86"],
            "icon": ["color": "#FFFFFF"]],
        "add8": [
            "background": ["color": "#BABABA"],
            "icon": ["color": "#FFFFFF"]]
    ]
}
